w10d01/rick-and-morty/config/routes.rb
Rails.application.routes.draw do
  resources :likes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "login", to: "users#index"
  # get "login", controller: 'users', action: :index

  # resources :characters, except: [:index, :show]
  # resources :characters

  # resources :locations

  resources :characters do
    resources :locations
  end
end

w10d01/rick-and-morty/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/rick-and-morty/app/models/character.rb
class Character < ApplicationRecord
  has_many :locations
end

w10d01/rick-and-morty/app/models/like.rb
class Like < ApplicationRecord
end

w10d01/rick-and-morty/app/models/location.rb
class Location < ApplicationRecord
  belongs_to :character
end

w10d01/rick-and-morty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/rick-and-morty/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all

    render json: @characters
  end
end

w10d01/rick-and-morty/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]

  # GET /likes or /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1 or /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to like_url(@like), notice: "Like was successfully created." }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to like_url(@like), notice: "Like was successfully updated." }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like.destroy

    respond_to do |format|
      format.html { redirect_to likes_url, notice: "Like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.fetch(:like, {})
    end
end

w10d01/rick-and-morty/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    # req.params.character_id
    
    @character = Character.find params[:character_id]
    @locations = @character.locations

    render json: {
      character: @character,
      locations: @locations,
      some_other_key: "even more fun stuff"
    }
  end
end

w10d01/rick-and-morty/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/rick-and-morty/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/rick-and-morty/app/helpers/likes_helper.rb
module LikesHelper
end

w10d01/rick-and-morty/app/helpers/locations_helper.rb
module LocationsHelper
end

w10d01/rick-and-morty/app/views/characters/index.html.erb
<h1>All the characters!</h1>

<% @characters.each do |character| %>
  <div class="character">
    <h2>Name: <%= character.name %></h2>
    <%= link_to "See the locations for this character", character_locations_path(character) %>
  </div>
<% end %>

w10d01/rick-and-morty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RickAndMorty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/rick-and-morty/app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w10d01/rick-and-morty/app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

w10d01/rick-and-morty/app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

w10d01/rick-and-morty/app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

w10d01/rick-and-morty/app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

w10d01/rick-and-morty/app/views/locations/_location.html.erb
<div class="location">
  <h2>Name: <%= location.name %></h2>
  <h2>Quote: <%= location.quote %></h2>
  <h2>Character: <%= location.character.name %></h2>
</div>

w10d01/rick-and-morty/app/views/locations/index.html.erb
<h1>All the locations for <%= @character.name %>!</h1>

<%= link_to "Back to characters", characters_path %>

<!-- <% @locations.each do |location| %>
  <%= render 'location', location: location %>
<% end %> -->

<%= render @locations %>