w10d01/superheroes/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :chocolates
  end

  resources :powers do
    resources :heros
  end
end

w10d01/superheroes/app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :power
end

w10d01/superheroes/app/models/power.rb
class Power < ApplicationRecord
  has_many :heros
end

w10d01/superheroes/app/controllers/admin/chocolates_controller.rb
class Admin::ChocolatesController < ApplicationController
  def index
  end
end

w10d01/superheroes/app/controllers/heros_controller.rb
class HerosController < ApplicationController
  def index
    @power = Power.find params[:power_id]
    @heros = @power.heros

    # render json: { power: @power, heros: @heros }
  end
end

w10d01/superheroes/app/controllers/powers_controller.rb
class PowersController < ApplicationController
  def index
    @powers = Power.all
  end
end

w10d01/superheroes/app/helpers/admin/chocolates_helper.rb
module Admin::ChocolatesHelper
end

w10d01/superheroes/app/helpers/heros_helper.rb
module HerosHelper
end

w10d01/superheroes/app/helpers/powers_helper.rb
module PowersHelper
end

w10d01/superheroes/app/views/admin/chocolates/index.html.erb
<h1>The admin page for Chocolates resource</h1>

w10d01/superheroes/app/views/heros/_hero.html.erb
<div class="hero">
  <h2>Name: <%= hero.name %></h2>
  <h2>Suffix: <%= hero.suffix %></h2>
  <h2>Prefix: <%= hero.prefix %></h2>
</div>

w10d01/superheroes/app/views/heros/index.html.erb
<h1>Heroes for <%= @power.power %></h1>

<%= link_to "All the powers", powers_path %>

<!-- <% @heros.each do |hero| %>
  <div class="hero">
    <h2>Name: <%= hero.name %></h2>
    <h2>Suffix: <%= hero.suffix %></h2>
    <h2>Prefix: <%= hero.prefix %></h2>
  </div>
<% end %> -->

<%= render @heros %>

w10d01/superheroes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/superheroes/app/views/powers/index.html.erb
<h1>All the powers</h1>

<% @powers.each do |power| %>
  <div class="power">
    <h2>Power: <%= power.power %></h2>
    <%= link_to "Heroes", power_heros_path(power) %>
  </div>
<% end %>